name: Deploy to Cloud Functions

permissions:
  id-token: write

on:
    # workflow_dispatch:  # Manually trigger the workflow
    # push:
    #     branches: [official_stats]
    #     paths:          
    #       - 'cloud_functions/**'  # Only trigger if changes are in the 'cloud-functions' directory
    workflow_run:
      workflows: [tests] # Trigger after the tests workflow completes
      types: [completed] # Only trigger on successful completion
    workflow_dispatch: # Manual trigger

jobs: # Sequence of jobs for this workflow
    deploy:
        runs-on: ubuntu-latest # Specify virtual machine for running the job
        steps: # Sequence of steps for this job
        - name: 'Checkout'
          uses: 'actions/checkout@v3'

        - name: 'Google auth'
          id: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
            workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
            service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
     
        - name: Deploy "official_stats"
          # No quote marks for secret in env-variable
          run: |
            gcloud functions deploy official_stats \
            --region europe-west1 \
            --source cloud_functions/official_stats \
            --trigger-http \
            --runtime python39 \
            --entry-point main \
            --allow-unauthenticated \
            --set-env-vars GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \