name: deploy_to_gcp

permissions:
  id-token: write

on:
  workflow_run:
    workflows: ['test_functions']
    types: [completed]
    branches: [main] # Only deploy automatically on main
  workflow_dispatch: # Manual trigger

jobs:
  deploy_to_gcp:
      # Only deploy if tests were successful or if manually triggered
      if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest # Specify virtual machine for running the job
      steps: # Sequence of steps for this job
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Deploy "database-endpoint-rev"
        run: |
          gcloud functions deploy database-endpoint-rev \
          --region=europe-west1 \
          --source=cloud_functions/database_endpoint \
          --trigger-http \
          --runtime=python39 \
          --entry-point=main \
          --set-env-vars GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
          --service-account='${{ secrets.WIF_SERVICE_ACCOUNT }}'
      
      - name: Deploy "ba-official-stats-rev"
        run: |
          gcloud functions deploy ba-official-stats-rev \
          --region=europe-west1 \
          --source=cloud_functions/ba_official_stats \
          --trigger-http \
          --runtime=python39 \
          --entry-point=main \
          --set-env-vars GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
          --service-account='${{ secrets.WIF_SERVICE_ACCOUNT }}'