name: test_functions

permissions:
  id-token: write

on:
  push:
        # branches: [official_stats]
        paths:
            - 'cloud_functions/**'   # Trigger on Cloud Function changes
            - '.github/workflows/**' # Trigger on workflow changes
  workflow_dispatch: # Manual trigger

jobs:
  # Perform linting and unittests
  test_official_stats:
          runs-on: ubuntu-latest
          steps:
              - name: 'Checkout'
                uses: 'actions/checkout@v3'

              - name: Set up Python
                uses: actions/setup-python@v4
                with:
                  python-version: '3.8'
              
              - name: Install dependencies
                run: |
                  python -m pip install --upgrade pip
                  pip install -r cloud_functions/official_stats/requirements.txt
                  pip install pylint
                  pip install pytest

              - name: Linting
                run: pylint cloud_functions/.
              
              - name: unittests
                run : pytest
